# MISCONFIG 1: Privileged Pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: privileged-app
  namespace: vuln-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: privileged-app
  template:
    metadata:
      labels:
        app: privileged-app
    spec:
      containers:
        - name: privileged-app
          image: docker.io/library/nginx:alpine
          securityContext:
            privileged: true
            runAsUser: 0
          resources:
            limits:
              cpu: "200m"
              memory: "128Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
---
# MISCONFIG 2: Wildcard RBAC
apiVersion: v1
kind: ServiceAccount
metadata:
  name: over-privileged-sa
  namespace: vuln-apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: over-privileged-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: over-privileged-sa
    namespace: vuln-apps
---
# MISCONFIG 3: Secrets in ENV
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-in-env
  namespace: vuln-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-in-env
  template:
    metadata:
      labels:
        app: secret-in-env
    spec:
      serviceAccountName: over-privileged-sa
      containers:
        - name: secret-in-env
          image: docker.io/library/nginx:alpine
          env:
            - name: DB_PASSWORD
              value: "SuperSecret123!"
            - name: API_KEY
              value: "sk-prod-abcd1234efgh5678"
            - name: AWS_SECRET_KEY
              value: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
          resources:
            limits:
              cpu: "200m"
              memory: "128Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"